[package]
name = "hello_blockchain"
version = "1.0.0"
authors = []

[addresses]
owner='0x43'

[dev-addresses]

[dependencies.AptosFramework]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = "mainnet"
subdir = "aptos-move/framework/aptos-framework"

[dev-dependencies]
